// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.milvus.grpc.schema

sealed abstract class FunctionType(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = io.milvus.grpc.schema.FunctionType
  type RecognizedType = io.milvus.grpc.schema.FunctionType.Recognized
  def isUnknown: _root_.scala.Boolean = false
  def isBm25: _root_.scala.Boolean = false
  def isTextEmbedding: _root_.scala.Boolean = false
  def isRerank: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[FunctionType] = io.milvus.grpc.schema.FunctionType
  final def asRecognized: _root_.scala.Option[io.milvus.grpc.schema.FunctionType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[io.milvus.grpc.schema.FunctionType.Recognized])
}

object FunctionType extends _root_.scalapb.GeneratedEnumCompanion[FunctionType] {
  sealed trait Recognized extends FunctionType
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[FunctionType] = this
  
  @SerialVersionUID(0L)
  case object Unknown extends FunctionType(0) with FunctionType.Recognized {
    val index = 0
    val name = "Unknown"
    override def isUnknown: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object BM25 extends FunctionType(1) with FunctionType.Recognized {
    val index = 1
    val name = "BM25"
    override def isBm25: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object TextEmbedding extends FunctionType(2) with FunctionType.Recognized {
    val index = 2
    val name = "TextEmbedding"
    override def isTextEmbedding: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Rerank extends FunctionType(3) with FunctionType.Recognized {
    val index = 3
    val name = "Rerank"
    override def isRerank: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends FunctionType(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(Unknown, BM25, TextEmbedding, Rerank)
  def fromValue(__value: _root_.scala.Int): FunctionType = __value match {
    case 0 => Unknown
    case 1 => BM25
    case 2 => TextEmbedding
    case 3 => Rerank
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = io.milvus.grpc.schema.SchemaProto.javaDescriptor.getEnumTypes().get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = io.milvus.grpc.schema.SchemaProto.scalaDescriptor.enums(1)
}