// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.milvus.grpc.schema

/** @param functions
  *   Currently only a single function is supported, and multiple functions
  * @param params
  *   may be supported in the future, so repeated is used here.
  */
@SerialVersionUID(0L)
final case class FunctionScore(
    functions: _root_.scala.Seq[io.milvus.grpc.schema.FunctionSchema] = _root_.scala.Seq.empty,
    params: _root_.scala.Seq[io.milvus.grpc.common.KeyValuePair] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[FunctionScore] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      functions.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      params.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      functions.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      params.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def clearFunctions = copy(functions = _root_.scala.Seq.empty)
    def addFunctions(__vs: io.milvus.grpc.schema.FunctionSchema *): FunctionScore = addAllFunctions(__vs)
    def addAllFunctions(__vs: Iterable[io.milvus.grpc.schema.FunctionSchema]): FunctionScore = copy(functions = functions ++ __vs)
    def withFunctions(__v: _root_.scala.Seq[io.milvus.grpc.schema.FunctionSchema]): FunctionScore = copy(functions = __v)
    def clearParams = copy(params = _root_.scala.Seq.empty)
    def addParams(__vs: io.milvus.grpc.common.KeyValuePair *): FunctionScore = addAllParams(__vs)
    def addAllParams(__vs: Iterable[io.milvus.grpc.common.KeyValuePair]): FunctionScore = copy(params = params ++ __vs)
    def withParams(__v: _root_.scala.Seq[io.milvus.grpc.common.KeyValuePair]): FunctionScore = copy(params = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => functions
        case 2 => params
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(functions.iterator.map(_.toPMessage).toVector)
        case 2 => _root_.scalapb.descriptors.PRepeated(params.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: io.milvus.grpc.schema.FunctionScore.type = io.milvus.grpc.schema.FunctionScore
    // @@protoc_insertion_point(GeneratedMessage[milvus.proto.schema.FunctionScore])
}

object FunctionScore extends scalapb.GeneratedMessageCompanion[io.milvus.grpc.schema.FunctionScore] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[io.milvus.grpc.schema.FunctionScore] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): io.milvus.grpc.schema.FunctionScore = {
    val __functions: _root_.scala.collection.immutable.VectorBuilder[io.milvus.grpc.schema.FunctionSchema] = new _root_.scala.collection.immutable.VectorBuilder[io.milvus.grpc.schema.FunctionSchema]
    val __params: _root_.scala.collection.immutable.VectorBuilder[io.milvus.grpc.common.KeyValuePair] = new _root_.scala.collection.immutable.VectorBuilder[io.milvus.grpc.common.KeyValuePair]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __functions += _root_.scalapb.LiteParser.readMessage[io.milvus.grpc.schema.FunctionSchema](_input__)
        case 18 =>
          __params += _root_.scalapb.LiteParser.readMessage[io.milvus.grpc.common.KeyValuePair](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    io.milvus.grpc.schema.FunctionScore(
        functions = __functions.result(),
        params = __params.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[io.milvus.grpc.schema.FunctionScore] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      io.milvus.grpc.schema.FunctionScore(
        functions = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[io.milvus.grpc.schema.FunctionSchema]]).getOrElse(_root_.scala.Seq.empty),
        params = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[io.milvus.grpc.common.KeyValuePair]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = io.milvus.grpc.schema.SchemaProto.javaDescriptor.getMessageTypes().get(2)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = io.milvus.grpc.schema.SchemaProto.scalaDescriptor.messages(2)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[?] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = io.milvus.grpc.schema.FunctionSchema
      case 2 => __out = io.milvus.grpc.common.KeyValuePair
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = io.milvus.grpc.schema.FunctionScore(
    functions = _root_.scala.Seq.empty,
    params = _root_.scala.Seq.empty
  )
  implicit class FunctionScoreLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, io.milvus.grpc.schema.FunctionScore]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, io.milvus.grpc.schema.FunctionScore](_l) {
    def functions: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[io.milvus.grpc.schema.FunctionSchema]] = field(_.functions)((c_, f_) => c_.copy(functions = f_))
    def params: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[io.milvus.grpc.common.KeyValuePair]] = field(_.params)((c_, f_) => c_.copy(params = f_))
  }
  final val FUNCTIONS_FIELD_NUMBER = 1
  final val PARAMS_FIELD_NUMBER = 2
  def of(
    functions: _root_.scala.Seq[io.milvus.grpc.schema.FunctionSchema],
    params: _root_.scala.Seq[io.milvus.grpc.common.KeyValuePair]
  ): _root_.io.milvus.grpc.schema.FunctionScore = _root_.io.milvus.grpc.schema.FunctionScore(
    functions,
    params
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[milvus.proto.schema.FunctionScore])
}
