// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.milvus.grpc.schema

@SerialVersionUID(0L)
final case class VectorArray(
    dim: _root_.scala.Long = 0L,
    data: _root_.scala.Seq[io.milvus.grpc.schema.VectorField] = _root_.scala.Seq.empty,
    elementType: io.milvus.grpc.schema.DataType = io.milvus.grpc.schema.DataType.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[VectorArray] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = dim
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(1, __value)
        }
      };
      data.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      
      {
        val __value = elementType.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(3, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = dim
        if (__v != 0L) {
          _output__.writeInt64(1, __v)
        }
      };
      data.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = elementType.value
        if (__v != 0) {
          _output__.writeEnum(3, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withDim(__v: _root_.scala.Long): VectorArray = copy(dim = __v)
    def clearData = copy(data = _root_.scala.Seq.empty)
    def addData(__vs: io.milvus.grpc.schema.VectorField *): VectorArray = addAllData(__vs)
    def addAllData(__vs: Iterable[io.milvus.grpc.schema.VectorField]): VectorArray = copy(data = data ++ __vs)
    def withData(__v: _root_.scala.Seq[io.milvus.grpc.schema.VectorField]): VectorArray = copy(data = __v)
    def withElementType(__v: io.milvus.grpc.schema.DataType): VectorArray = copy(elementType = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = dim
          if (__t != 0L) __t else null
        }
        case 2 => data
        case 3 => {
          val __t = elementType.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PLong(dim)
        case 2 => _root_.scalapb.descriptors.PRepeated(data.iterator.map(_.toPMessage).toVector)
        case 3 => _root_.scalapb.descriptors.PEnum(elementType.scalaValueDescriptor)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: io.milvus.grpc.schema.VectorArray.type = io.milvus.grpc.schema.VectorArray
    // @@protoc_insertion_point(GeneratedMessage[milvus.proto.schema.VectorArray])
}

object VectorArray extends scalapb.GeneratedMessageCompanion[io.milvus.grpc.schema.VectorArray] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[io.milvus.grpc.schema.VectorArray] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): io.milvus.grpc.schema.VectorArray = {
    var __dim: _root_.scala.Long = 0L
    val __data: _root_.scala.collection.immutable.VectorBuilder[io.milvus.grpc.schema.VectorField] = new _root_.scala.collection.immutable.VectorBuilder[io.milvus.grpc.schema.VectorField]
    var __elementType: io.milvus.grpc.schema.DataType = io.milvus.grpc.schema.DataType.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __dim = _input__.readInt64()
        case 18 =>
          __data += _root_.scalapb.LiteParser.readMessage[io.milvus.grpc.schema.VectorField](_input__)
        case 24 =>
          __elementType = io.milvus.grpc.schema.DataType.fromValue(_input__.readEnum())
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    io.milvus.grpc.schema.VectorArray(
        dim = __dim,
        data = __data.result(),
        elementType = __elementType,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[io.milvus.grpc.schema.VectorArray] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      io.milvus.grpc.schema.VectorArray(
        dim = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        data = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[io.milvus.grpc.schema.VectorField]]).getOrElse(_root_.scala.Seq.empty),
        elementType = io.milvus.grpc.schema.DataType.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(io.milvus.grpc.schema.DataType.None.scalaValueDescriptor).number)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = io.milvus.grpc.schema.SchemaProto.javaDescriptor.getMessageTypes().get(19)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = io.milvus.grpc.schema.SchemaProto.scalaDescriptor.messages(19)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[?] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = io.milvus.grpc.schema.VectorField
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 3 => io.milvus.grpc.schema.DataType
    }
  }
  lazy val defaultInstance = io.milvus.grpc.schema.VectorArray(
    dim = 0L,
    data = _root_.scala.Seq.empty,
    elementType = io.milvus.grpc.schema.DataType.None
  )
  implicit class VectorArrayLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, io.milvus.grpc.schema.VectorArray]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, io.milvus.grpc.schema.VectorArray](_l) {
    def dim: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.dim)((c_, f_) => c_.copy(dim = f_))
    def data: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[io.milvus.grpc.schema.VectorField]] = field(_.data)((c_, f_) => c_.copy(data = f_))
    def elementType: _root_.scalapb.lenses.Lens[UpperPB, io.milvus.grpc.schema.DataType] = field(_.elementType)((c_, f_) => c_.copy(elementType = f_))
  }
  final val DIM_FIELD_NUMBER = 1
  final val DATA_FIELD_NUMBER = 2
  final val ELEMENT_TYPE_FIELD_NUMBER = 3
  def of(
    dim: _root_.scala.Long,
    data: _root_.scala.Seq[io.milvus.grpc.schema.VectorField],
    elementType: io.milvus.grpc.schema.DataType
  ): _root_.io.milvus.grpc.schema.VectorArray = _root_.io.milvus.grpc.schema.VectorArray(
    dim,
    data,
    elementType
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[milvus.proto.schema.VectorArray])
}
