// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package milvus.proto.msg

import milvus.proto.msg

@SerialVersionUID(0L)
final case class DataNodeTtMsg(
    base: _root_.scala.Option[io.milvus.grpc.common.MsgBase] = _root_.scala.None,
    channelName: _root_.scala.Predef.String = "",
    timestamp: _root_.scala.Long = 0L,
    segmentsStats: _root_.scala.Seq[io.milvus.grpc.common.SegmentStats] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[DataNodeTtMsg] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      if (base.isDefined) {
        val __value = base.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = channelName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = timestamp
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt64Size(3, __value)
        }
      };
      segmentsStats.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      base.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = channelName
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = timestamp
        if (__v != 0L) {
          _output__.writeUInt64(3, __v)
        }
      };
      segmentsStats.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def getBase: io.milvus.grpc.common.MsgBase = base.getOrElse(io.milvus.grpc.common.MsgBase.defaultInstance)
    def clearBase: DataNodeTtMsg = copy(base = _root_.scala.None)
    def withBase(__v: io.milvus.grpc.common.MsgBase): DataNodeTtMsg = copy(base = Option(__v))
    def withChannelName(__v: _root_.scala.Predef.String): DataNodeTtMsg = copy(channelName = __v)
    def withTimestamp(__v: _root_.scala.Long): DataNodeTtMsg = copy(timestamp = __v)
    def clearSegmentsStats = copy(segmentsStats = _root_.scala.Seq.empty)
    def addSegmentsStats(__vs: io.milvus.grpc.common.SegmentStats *): DataNodeTtMsg = addAllSegmentsStats(__vs)
    def addAllSegmentsStats(__vs: Iterable[io.milvus.grpc.common.SegmentStats]): DataNodeTtMsg = copy(segmentsStats = segmentsStats ++ __vs)
    def withSegmentsStats(__v: _root_.scala.Seq[io.milvus.grpc.common.SegmentStats]): DataNodeTtMsg = copy(segmentsStats = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => base.orNull
        case 2 => {
          val __t = channelName
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = timestamp
          if (__t != 0L) __t else null
        }
        case 4 => segmentsStats
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => base.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => _root_.scalapb.descriptors.PString(channelName)
        case 3 => _root_.scalapb.descriptors.PLong(timestamp)
        case 4 => _root_.scalapb.descriptors.PRepeated(segmentsStats.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: DataNodeTtMsg.type = msg.DataNodeTtMsg
    // @@protoc_insertion_point(GeneratedMessage[milvus.proto.msg.DataNodeTtMsg])
}

object DataNodeTtMsg extends scalapb.GeneratedMessageCompanion[DataNodeTtMsg] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[DataNodeTtMsg] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): DataNodeTtMsg = {
    var __base: _root_.scala.Option[io.milvus.grpc.common.MsgBase] = _root_.scala.None
    var __channelName: _root_.scala.Predef.String = ""
    var __timestamp: _root_.scala.Long = 0L
    val __segmentsStats: _root_.scala.collection.immutable.VectorBuilder[io.milvus.grpc.common.SegmentStats] = new _root_.scala.collection.immutable.VectorBuilder[io.milvus.grpc.common.SegmentStats]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __base = _root_.scala.Option(__base.fold(_root_.scalapb.LiteParser.readMessage[io.milvus.grpc.common.MsgBase](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 18 =>
          __channelName = _input__.readStringRequireUtf8()
        case 24 =>
          __timestamp = _input__.readUInt64()
        case 34 =>
          __segmentsStats += _root_.scalapb.LiteParser.readMessage[io.milvus.grpc.common.SegmentStats](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    DataNodeTtMsg(
        base = __base,
        channelName = __channelName,
        timestamp = __timestamp,
        segmentsStats = __segmentsStats.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[DataNodeTtMsg] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      DataNodeTtMsg(
        base = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[io.milvus.grpc.common.MsgBase]]),
        channelName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        timestamp = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        segmentsStats = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Seq[io.milvus.grpc.common.SegmentStats]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = MsgProto.javaDescriptor.getMessageTypes().get(8)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = msg.MsgProto.scalaDescriptor.messages(8)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[?] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = io.milvus.grpc.common.MsgBase
      case 4 => __out = io.milvus.grpc.common.SegmentStats
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = DataNodeTtMsg(
    base = _root_.scala.None,
    channelName = "",
    timestamp = 0L,
    segmentsStats = _root_.scala.Seq.empty
  )
  implicit class DataNodeTtMsgLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, DataNodeTtMsg]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, DataNodeTtMsg](_l) {
    def base: _root_.scalapb.lenses.Lens[UpperPB, io.milvus.grpc.common.MsgBase] = field(_.getBase)((c_, f_) => c_.copy(base = _root_.scala.Option(f_)))
    def optionalBase: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[io.milvus.grpc.common.MsgBase]] = field(_.base)((c_, f_) => c_.copy(base = f_))
    def channelName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.channelName)((c_, f_) => c_.copy(channelName = f_))
    def timestamp: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.timestamp)((c_, f_) => c_.copy(timestamp = f_))
    def segmentsStats: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[io.milvus.grpc.common.SegmentStats]] = field(_.segmentsStats)((c_, f_) => c_.copy(segmentsStats = f_))
  }
  final val BASE_FIELD_NUMBER = 1
  final val CHANNEL_NAME_FIELD_NUMBER = 2
  final val TIMESTAMP_FIELD_NUMBER = 3
  final val SEGMENTS_STATS_FIELD_NUMBER = 4
  def of(
    base: _root_.scala.Option[io.milvus.grpc.common.MsgBase],
    channelName: _root_.scala.Predef.String,
    timestamp: _root_.scala.Long,
    segmentsStats: _root_.scala.Seq[io.milvus.grpc.common.SegmentStats]
  ): DataNodeTtMsg = DataNodeTtMsg(
    base,
    channelName,
    timestamp,
    segmentsStats
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[milvus.proto.msg.DataNodeTtMsg])
}
