// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.milvus.grpc.milvus

@SerialVersionUID(0L)
final case class ComponentInfo(
    nodeID: _root_.scala.Long = 0L,
    role: _root_.scala.Predef.String = "",
    stateCode: io.milvus.grpc.common.StateCode = io.milvus.grpc.common.StateCode.Initializing,
    extraInfo: _root_.scala.Seq[io.milvus.grpc.common.KeyValuePair] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ComponentInfo] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = nodeID
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(1, __value)
        }
      };
      
      {
        val __value = role
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = stateCode.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(3, __value)
        }
      };
      extraInfo.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = nodeID
        if (__v != 0L) {
          _output__.writeInt64(1, __v)
        }
      };
      {
        val __v = role
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = stateCode.value
        if (__v != 0) {
          _output__.writeEnum(3, __v)
        }
      };
      extraInfo.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withNodeID(__v: _root_.scala.Long): ComponentInfo = copy(nodeID = __v)
    def withRole(__v: _root_.scala.Predef.String): ComponentInfo = copy(role = __v)
    def withStateCode(__v: io.milvus.grpc.common.StateCode): ComponentInfo = copy(stateCode = __v)
    def clearExtraInfo = copy(extraInfo = _root_.scala.Seq.empty)
    def addExtraInfo(__vs: io.milvus.grpc.common.KeyValuePair *): ComponentInfo = addAllExtraInfo(__vs)
    def addAllExtraInfo(__vs: Iterable[io.milvus.grpc.common.KeyValuePair]): ComponentInfo = copy(extraInfo = extraInfo ++ __vs)
    def withExtraInfo(__v: _root_.scala.Seq[io.milvus.grpc.common.KeyValuePair]): ComponentInfo = copy(extraInfo = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = nodeID
          if (__t != 0L) __t else null
        }
        case 2 => {
          val __t = role
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = stateCode.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 4 => extraInfo
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PLong(nodeID)
        case 2 => _root_.scalapb.descriptors.PString(role)
        case 3 => _root_.scalapb.descriptors.PEnum(stateCode.scalaValueDescriptor)
        case 4 => _root_.scalapb.descriptors.PRepeated(extraInfo.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: io.milvus.grpc.milvus.ComponentInfo.type = io.milvus.grpc.milvus.ComponentInfo
    // @@protoc_insertion_point(GeneratedMessage[milvus.proto.milvus.ComponentInfo])
}

object ComponentInfo extends scalapb.GeneratedMessageCompanion[io.milvus.grpc.milvus.ComponentInfo] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[io.milvus.grpc.milvus.ComponentInfo] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): io.milvus.grpc.milvus.ComponentInfo = {
    var __nodeID: _root_.scala.Long = 0L
    var __role: _root_.scala.Predef.String = ""
    var __stateCode: io.milvus.grpc.common.StateCode = io.milvus.grpc.common.StateCode.Initializing
    val __extraInfo: _root_.scala.collection.immutable.VectorBuilder[io.milvus.grpc.common.KeyValuePair] = new _root_.scala.collection.immutable.VectorBuilder[io.milvus.grpc.common.KeyValuePair]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __nodeID = _input__.readInt64()
        case 18 =>
          __role = _input__.readStringRequireUtf8()
        case 24 =>
          __stateCode = io.milvus.grpc.common.StateCode.fromValue(_input__.readEnum())
        case 34 =>
          __extraInfo += _root_.scalapb.LiteParser.readMessage[io.milvus.grpc.common.KeyValuePair](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    io.milvus.grpc.milvus.ComponentInfo(
        nodeID = __nodeID,
        role = __role,
        stateCode = __stateCode,
        extraInfo = __extraInfo.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[io.milvus.grpc.milvus.ComponentInfo] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      io.milvus.grpc.milvus.ComponentInfo(
        nodeID = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        role = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        stateCode = io.milvus.grpc.common.StateCode.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(io.milvus.grpc.common.StateCode.Initializing.scalaValueDescriptor).number),
        extraInfo = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Seq[io.milvus.grpc.common.KeyValuePair]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = io.milvus.grpc.milvus.MilvusProto.javaDescriptor.getMessageTypes().get(82)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = io.milvus.grpc.milvus.MilvusProto.scalaDescriptor.messages(82)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[?] = null
    (__number: @_root_.scala.unchecked) match {
      case 4 => __out = io.milvus.grpc.common.KeyValuePair
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 3 => io.milvus.grpc.common.StateCode
    }
  }
  lazy val defaultInstance = io.milvus.grpc.milvus.ComponentInfo(
    nodeID = 0L,
    role = "",
    stateCode = io.milvus.grpc.common.StateCode.Initializing,
    extraInfo = _root_.scala.Seq.empty
  )
  implicit class ComponentInfoLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, io.milvus.grpc.milvus.ComponentInfo]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, io.milvus.grpc.milvus.ComponentInfo](_l) {
    def nodeID: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.nodeID)((c_, f_) => c_.copy(nodeID = f_))
    def role: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.role)((c_, f_) => c_.copy(role = f_))
    def stateCode: _root_.scalapb.lenses.Lens[UpperPB, io.milvus.grpc.common.StateCode] = field(_.stateCode)((c_, f_) => c_.copy(stateCode = f_))
    def extraInfo: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[io.milvus.grpc.common.KeyValuePair]] = field(_.extraInfo)((c_, f_) => c_.copy(extraInfo = f_))
  }
  final val NODEID_FIELD_NUMBER = 1
  final val ROLE_FIELD_NUMBER = 2
  final val STATE_CODE_FIELD_NUMBER = 3
  final val EXTRA_INFO_FIELD_NUMBER = 4
  def of(
    nodeID: _root_.scala.Long,
    role: _root_.scala.Predef.String,
    stateCode: io.milvus.grpc.common.StateCode,
    extraInfo: _root_.scala.Seq[io.milvus.grpc.common.KeyValuePair]
  ): _root_.io.milvus.grpc.milvus.ComponentInfo = _root_.io.milvus.grpc.milvus.ComponentInfo(
    nodeID,
    role,
    stateCode,
    extraInfo
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[milvus.proto.milvus.ComponentInfo])
}
