// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.milvus.grpc.milvus

@SerialVersionUID(0L)
final case class DescribeDatabaseResponse(
    status: _root_.scala.Option[io.milvus.grpc.common.Status] = _root_.scala.None,
    dbName: _root_.scala.Predef.String = "",
    dbID: _root_.scala.Long = 0L,
    createdTimestamp: _root_.scala.Long = 0L,
    properties: _root_.scala.Seq[io.milvus.grpc.common.KeyValuePair] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[DescribeDatabaseResponse] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      if (status.isDefined) {
        val __value = status.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = dbName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = dbID
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(3, __value)
        }
      };
      
      {
        val __value = createdTimestamp
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt64Size(4, __value)
        }
      };
      properties.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      status.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = dbName
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = dbID
        if (__v != 0L) {
          _output__.writeInt64(3, __v)
        }
      };
      {
        val __v = createdTimestamp
        if (__v != 0L) {
          _output__.writeUInt64(4, __v)
        }
      };
      properties.foreach { __v =>
        val __m = __v
        _output__.writeTag(5, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def getStatus: io.milvus.grpc.common.Status = status.getOrElse(io.milvus.grpc.common.Status.defaultInstance)
    def clearStatus: DescribeDatabaseResponse = copy(status = _root_.scala.None)
    def withStatus(__v: io.milvus.grpc.common.Status): DescribeDatabaseResponse = copy(status = Option(__v))
    def withDbName(__v: _root_.scala.Predef.String): DescribeDatabaseResponse = copy(dbName = __v)
    def withDbID(__v: _root_.scala.Long): DescribeDatabaseResponse = copy(dbID = __v)
    def withCreatedTimestamp(__v: _root_.scala.Long): DescribeDatabaseResponse = copy(createdTimestamp = __v)
    def clearProperties = copy(properties = _root_.scala.Seq.empty)
    def addProperties(__vs: io.milvus.grpc.common.KeyValuePair *): DescribeDatabaseResponse = addAllProperties(__vs)
    def addAllProperties(__vs: Iterable[io.milvus.grpc.common.KeyValuePair]): DescribeDatabaseResponse = copy(properties = properties ++ __vs)
    def withProperties(__v: _root_.scala.Seq[io.milvus.grpc.common.KeyValuePair]): DescribeDatabaseResponse = copy(properties = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => status.orNull
        case 2 => {
          val __t = dbName
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = dbID
          if (__t != 0L) __t else null
        }
        case 4 => {
          val __t = createdTimestamp
          if (__t != 0L) __t else null
        }
        case 5 => properties
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => status.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => _root_.scalapb.descriptors.PString(dbName)
        case 3 => _root_.scalapb.descriptors.PLong(dbID)
        case 4 => _root_.scalapb.descriptors.PLong(createdTimestamp)
        case 5 => _root_.scalapb.descriptors.PRepeated(properties.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: io.milvus.grpc.milvus.DescribeDatabaseResponse.type = io.milvus.grpc.milvus.DescribeDatabaseResponse
    // @@protoc_insertion_point(GeneratedMessage[milvus.proto.milvus.DescribeDatabaseResponse])
}

object DescribeDatabaseResponse extends scalapb.GeneratedMessageCompanion[io.milvus.grpc.milvus.DescribeDatabaseResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[io.milvus.grpc.milvus.DescribeDatabaseResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): io.milvus.grpc.milvus.DescribeDatabaseResponse = {
    var __status: _root_.scala.Option[io.milvus.grpc.common.Status] = _root_.scala.None
    var __dbName: _root_.scala.Predef.String = ""
    var __dbID: _root_.scala.Long = 0L
    var __createdTimestamp: _root_.scala.Long = 0L
    val __properties: _root_.scala.collection.immutable.VectorBuilder[io.milvus.grpc.common.KeyValuePair] = new _root_.scala.collection.immutable.VectorBuilder[io.milvus.grpc.common.KeyValuePair]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __status = _root_.scala.Option(__status.fold(_root_.scalapb.LiteParser.readMessage[io.milvus.grpc.common.Status](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 18 =>
          __dbName = _input__.readStringRequireUtf8()
        case 24 =>
          __dbID = _input__.readInt64()
        case 32 =>
          __createdTimestamp = _input__.readUInt64()
        case 42 =>
          __properties += _root_.scalapb.LiteParser.readMessage[io.milvus.grpc.common.KeyValuePair](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    io.milvus.grpc.milvus.DescribeDatabaseResponse(
        status = __status,
        dbName = __dbName,
        dbID = __dbID,
        createdTimestamp = __createdTimestamp,
        properties = __properties.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[io.milvus.grpc.milvus.DescribeDatabaseResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      io.milvus.grpc.milvus.DescribeDatabaseResponse(
        status = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[io.milvus.grpc.common.Status]]),
        dbName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        dbID = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        createdTimestamp = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        properties = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Seq[io.milvus.grpc.common.KeyValuePair]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = io.milvus.grpc.milvus.MilvusProto.javaDescriptor.getMessageTypes().get(175)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = io.milvus.grpc.milvus.MilvusProto.scalaDescriptor.messages(175)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[?] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = io.milvus.grpc.common.Status
      case 5 => __out = io.milvus.grpc.common.KeyValuePair
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = io.milvus.grpc.milvus.DescribeDatabaseResponse(
    status = _root_.scala.None,
    dbName = "",
    dbID = 0L,
    createdTimestamp = 0L,
    properties = _root_.scala.Seq.empty
  )
  implicit class DescribeDatabaseResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, io.milvus.grpc.milvus.DescribeDatabaseResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, io.milvus.grpc.milvus.DescribeDatabaseResponse](_l) {
    def status: _root_.scalapb.lenses.Lens[UpperPB, io.milvus.grpc.common.Status] = field(_.getStatus)((c_, f_) => c_.copy(status = _root_.scala.Option(f_)))
    def optionalStatus: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[io.milvus.grpc.common.Status]] = field(_.status)((c_, f_) => c_.copy(status = f_))
    def dbName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.dbName)((c_, f_) => c_.copy(dbName = f_))
    def dbID: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.dbID)((c_, f_) => c_.copy(dbID = f_))
    def createdTimestamp: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.createdTimestamp)((c_, f_) => c_.copy(createdTimestamp = f_))
    def properties: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[io.milvus.grpc.common.KeyValuePair]] = field(_.properties)((c_, f_) => c_.copy(properties = f_))
  }
  final val STATUS_FIELD_NUMBER = 1
  final val DB_NAME_FIELD_NUMBER = 2
  final val DBID_FIELD_NUMBER = 3
  final val CREATED_TIMESTAMP_FIELD_NUMBER = 4
  final val PROPERTIES_FIELD_NUMBER = 5
  def of(
    status: _root_.scala.Option[io.milvus.grpc.common.Status],
    dbName: _root_.scala.Predef.String,
    dbID: _root_.scala.Long,
    createdTimestamp: _root_.scala.Long,
    properties: _root_.scala.Seq[io.milvus.grpc.common.KeyValuePair]
  ): _root_.io.milvus.grpc.milvus.DescribeDatabaseResponse = _root_.io.milvus.grpc.milvus.DescribeDatabaseResponse(
    status,
    dbName,
    dbID,
    createdTimestamp,
    properties
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[milvus.proto.milvus.DescribeDatabaseResponse])
}
