// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.milvus.grpc.milvus

@SerialVersionUID(0L)
final case class ManualCompactionRequest(
    collectionID: _root_.scala.Long = 0L,
    timetravel: _root_.scala.Long = 0L,
    majorCompaction: _root_.scala.Boolean = false,
    collectionName: _root_.scala.Predef.String = "",
    dbName: _root_.scala.Predef.String = "",
    partitionId: _root_.scala.Long = 0L,
    channel: _root_.scala.Predef.String = "",
    segmentIds: _root_.scala.Seq[_root_.scala.Long] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ManualCompactionRequest] {
    private[this] def segmentIdsSerializedSize = {
      if (__segmentIdsSerializedSizeField == 0) __segmentIdsSerializedSizeField = {
        var __s: _root_.scala.Int = 0
        segmentIds.foreach(__i => __s += _root_.com.google.protobuf.CodedOutputStream.computeInt64SizeNoTag(__i))
        __s
      }
      __segmentIdsSerializedSizeField
    }
    @transient private[this] var __segmentIdsSerializedSizeField: _root_.scala.Int = 0
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = collectionID
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(1, __value)
        }
      };
      
      {
        val __value = timetravel
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt64Size(2, __value)
        }
      };
      
      {
        val __value = majorCompaction
        if (__value != false) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeBoolSize(3, __value)
        }
      };
      
      {
        val __value = collectionName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      
      {
        val __value = dbName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      
      {
        val __value = partitionId
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(6, __value)
        }
      };
      
      {
        val __value = channel
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(7, __value)
        }
      };
      if (segmentIds.nonEmpty) {
        val __localsize = segmentIdsSerializedSize
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__localsize) + __localsize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = collectionID
        if (__v != 0L) {
          _output__.writeInt64(1, __v)
        }
      };
      {
        val __v = timetravel
        if (__v != 0L) {
          _output__.writeUInt64(2, __v)
        }
      };
      {
        val __v = majorCompaction
        if (__v != false) {
          _output__.writeBool(3, __v)
        }
      };
      {
        val __v = collectionName
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      {
        val __v = dbName
        if (!__v.isEmpty) {
          _output__.writeString(5, __v)
        }
      };
      {
        val __v = partitionId
        if (__v != 0L) {
          _output__.writeInt64(6, __v)
        }
      };
      {
        val __v = channel
        if (!__v.isEmpty) {
          _output__.writeString(7, __v)
        }
      };
      if (segmentIds.nonEmpty) {
        _output__.writeTag(8, 2)
        _output__.writeUInt32NoTag(segmentIdsSerializedSize)
        segmentIds.foreach(_output__.writeInt64NoTag)
      };
      unknownFields.writeTo(_output__)
    }
    def withCollectionID(__v: _root_.scala.Long): ManualCompactionRequest = copy(collectionID = __v)
    def withTimetravel(__v: _root_.scala.Long): ManualCompactionRequest = copy(timetravel = __v)
    def withMajorCompaction(__v: _root_.scala.Boolean): ManualCompactionRequest = copy(majorCompaction = __v)
    def withCollectionName(__v: _root_.scala.Predef.String): ManualCompactionRequest = copy(collectionName = __v)
    def withDbName(__v: _root_.scala.Predef.String): ManualCompactionRequest = copy(dbName = __v)
    def withPartitionId(__v: _root_.scala.Long): ManualCompactionRequest = copy(partitionId = __v)
    def withChannel(__v: _root_.scala.Predef.String): ManualCompactionRequest = copy(channel = __v)
    def clearSegmentIds = copy(segmentIds = _root_.scala.Seq.empty)
    def addSegmentIds(__vs: _root_.scala.Long *): ManualCompactionRequest = addAllSegmentIds(__vs)
    def addAllSegmentIds(__vs: Iterable[_root_.scala.Long]): ManualCompactionRequest = copy(segmentIds = segmentIds ++ __vs)
    def withSegmentIds(__v: _root_.scala.Seq[_root_.scala.Long]): ManualCompactionRequest = copy(segmentIds = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = collectionID
          if (__t != 0L) __t else null
        }
        case 2 => {
          val __t = timetravel
          if (__t != 0L) __t else null
        }
        case 3 => {
          val __t = majorCompaction
          if (__t != false) __t else null
        }
        case 4 => {
          val __t = collectionName
          if (__t != "") __t else null
        }
        case 5 => {
          val __t = dbName
          if (__t != "") __t else null
        }
        case 6 => {
          val __t = partitionId
          if (__t != 0L) __t else null
        }
        case 7 => {
          val __t = channel
          if (__t != "") __t else null
        }
        case 8 => segmentIds
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PLong(collectionID)
        case 2 => _root_.scalapb.descriptors.PLong(timetravel)
        case 3 => _root_.scalapb.descriptors.PBoolean(majorCompaction)
        case 4 => _root_.scalapb.descriptors.PString(collectionName)
        case 5 => _root_.scalapb.descriptors.PString(dbName)
        case 6 => _root_.scalapb.descriptors.PLong(partitionId)
        case 7 => _root_.scalapb.descriptors.PString(channel)
        case 8 => _root_.scalapb.descriptors.PRepeated(segmentIds.iterator.map(_root_.scalapb.descriptors.PLong(_)).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: io.milvus.grpc.milvus.ManualCompactionRequest.type = io.milvus.grpc.milvus.ManualCompactionRequest
    // @@protoc_insertion_point(GeneratedMessage[milvus.proto.milvus.ManualCompactionRequest])
}

object ManualCompactionRequest extends scalapb.GeneratedMessageCompanion[io.milvus.grpc.milvus.ManualCompactionRequest] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[io.milvus.grpc.milvus.ManualCompactionRequest] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): io.milvus.grpc.milvus.ManualCompactionRequest = {
    var __collectionID: _root_.scala.Long = 0L
    var __timetravel: _root_.scala.Long = 0L
    var __majorCompaction: _root_.scala.Boolean = false
    var __collectionName: _root_.scala.Predef.String = ""
    var __dbName: _root_.scala.Predef.String = ""
    var __partitionId: _root_.scala.Long = 0L
    var __channel: _root_.scala.Predef.String = ""
    val __segmentIds: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Long] = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Long]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __collectionID = _input__.readInt64()
        case 16 =>
          __timetravel = _input__.readUInt64()
        case 24 =>
          __majorCompaction = _input__.readBool()
        case 34 =>
          __collectionName = _input__.readStringRequireUtf8()
        case 42 =>
          __dbName = _input__.readStringRequireUtf8()
        case 48 =>
          __partitionId = _input__.readInt64()
        case 58 =>
          __channel = _input__.readStringRequireUtf8()
        case 64 =>
          __segmentIds += _input__.readInt64()
        case 66 => {
          val length = _input__.readRawVarint32()
          val oldLimit = _input__.pushLimit(length)
          while (_input__.getBytesUntilLimit > 0) {
            __segmentIds += _input__.readInt64()
          }
          _input__.popLimit(oldLimit)
        }
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    io.milvus.grpc.milvus.ManualCompactionRequest(
        collectionID = __collectionID,
        timetravel = __timetravel,
        majorCompaction = __majorCompaction,
        collectionName = __collectionName,
        dbName = __dbName,
        partitionId = __partitionId,
        channel = __channel,
        segmentIds = __segmentIds.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[io.milvus.grpc.milvus.ManualCompactionRequest] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      io.milvus.grpc.milvus.ManualCompactionRequest(
        collectionID = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        timetravel = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        majorCompaction = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Boolean]).getOrElse(false),
        collectionName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        dbName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        partitionId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        channel = __fieldsMap.get(scalaDescriptor.findFieldByNumber(7).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        segmentIds = __fieldsMap.get(scalaDescriptor.findFieldByNumber(8).get).map(_.as[_root_.scala.Seq[_root_.scala.Long]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = io.milvus.grpc.milvus.MilvusProto.javaDescriptor.getMessageTypes().get(86)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = io.milvus.grpc.milvus.MilvusProto.scalaDescriptor.messages(86)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = io.milvus.grpc.milvus.ManualCompactionRequest(
    collectionID = 0L,
    timetravel = 0L,
    majorCompaction = false,
    collectionName = "",
    dbName = "",
    partitionId = 0L,
    channel = "",
    segmentIds = _root_.scala.Seq.empty
  )
  implicit class ManualCompactionRequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, io.milvus.grpc.milvus.ManualCompactionRequest]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, io.milvus.grpc.milvus.ManualCompactionRequest](_l) {
    def collectionID: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.collectionID)((c_, f_) => c_.copy(collectionID = f_))
    def timetravel: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.timetravel)((c_, f_) => c_.copy(timetravel = f_))
    def majorCompaction: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Boolean] = field(_.majorCompaction)((c_, f_) => c_.copy(majorCompaction = f_))
    def collectionName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.collectionName)((c_, f_) => c_.copy(collectionName = f_))
    def dbName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.dbName)((c_, f_) => c_.copy(dbName = f_))
    def partitionId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.partitionId)((c_, f_) => c_.copy(partitionId = f_))
    def channel: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.channel)((c_, f_) => c_.copy(channel = f_))
    def segmentIds: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Long]] = field(_.segmentIds)((c_, f_) => c_.copy(segmentIds = f_))
  }
  final val COLLECTIONID_FIELD_NUMBER = 1
  final val TIMETRAVEL_FIELD_NUMBER = 2
  final val MAJORCOMPACTION_FIELD_NUMBER = 3
  final val COLLECTION_NAME_FIELD_NUMBER = 4
  final val DB_NAME_FIELD_NUMBER = 5
  final val PARTITION_ID_FIELD_NUMBER = 6
  final val CHANNEL_FIELD_NUMBER = 7
  final val SEGMENT_IDS_FIELD_NUMBER = 8
  def of(
    collectionID: _root_.scala.Long,
    timetravel: _root_.scala.Long,
    majorCompaction: _root_.scala.Boolean,
    collectionName: _root_.scala.Predef.String,
    dbName: _root_.scala.Predef.String,
    partitionId: _root_.scala.Long,
    channel: _root_.scala.Predef.String,
    segmentIds: _root_.scala.Seq[_root_.scala.Long]
  ): _root_.io.milvus.grpc.milvus.ManualCompactionRequest = _root_.io.milvus.grpc.milvus.ManualCompactionRequest(
    collectionID,
    timetravel,
    majorCompaction,
    collectionName,
    dbName,
    partitionId,
    channel,
    segmentIds
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[milvus.proto.milvus.ManualCompactionRequest])
}
