// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.milvus.grpc.milvus

sealed abstract class OperatePrivilegeType(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = io.milvus.grpc.milvus.OperatePrivilegeType
  type RecognizedType = io.milvus.grpc.milvus.OperatePrivilegeType.Recognized
  def isGrant: _root_.scala.Boolean = false
  def isRevoke: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[OperatePrivilegeType] = io.milvus.grpc.milvus.OperatePrivilegeType
  final def asRecognized: _root_.scala.Option[io.milvus.grpc.milvus.OperatePrivilegeType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[io.milvus.grpc.milvus.OperatePrivilegeType.Recognized])
}

object OperatePrivilegeType extends _root_.scalapb.GeneratedEnumCompanion[OperatePrivilegeType] {
  sealed trait Recognized extends OperatePrivilegeType
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[OperatePrivilegeType] = this
  
  @SerialVersionUID(0L)
  case object Grant extends OperatePrivilegeType(0) with OperatePrivilegeType.Recognized {
    val index = 0
    val name = "Grant"
    override def isGrant: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Revoke extends OperatePrivilegeType(1) with OperatePrivilegeType.Recognized {
    val index = 1
    val name = "Revoke"
    override def isRevoke: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends OperatePrivilegeType(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(Grant, Revoke)
  def fromValue(__value: _root_.scala.Int): OperatePrivilegeType = __value match {
    case 0 => Grant
    case 1 => Revoke
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = io.milvus.grpc.milvus.MilvusProto.javaDescriptor.getEnumTypes().get(4)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = io.milvus.grpc.milvus.MilvusProto.scalaDescriptor.enums(4)
}