// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.milvus.grpc.milvus

/** @param base
  *   Not useful for now
  * @param role
  *   role
  * @param grantor
  *   privilege
  * @param type
  *   operation type
  * @param dbName
  *   db name
  * @param collectionName
  *   collection name
  */
@SerialVersionUID(0L)
final case class OperatePrivilegeV2Request(
    base: _root_.scala.Option[io.milvus.grpc.common.MsgBase] = _root_.scala.None,
    role: _root_.scala.Option[io.milvus.grpc.milvus.RoleEntity] = _root_.scala.None,
    grantor: _root_.scala.Option[io.milvus.grpc.milvus.GrantorEntity] = _root_.scala.None,
    `type`: io.milvus.grpc.milvus.OperatePrivilegeType = io.milvus.grpc.milvus.OperatePrivilegeType.Grant,
    dbName: _root_.scala.Predef.String = "",
    collectionName: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[OperatePrivilegeV2Request] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      if (base.isDefined) {
        val __value = base.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (role.isDefined) {
        val __value = role.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (grantor.isDefined) {
        val __value = grantor.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      
      {
        val __value = `type`.value
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeEnumSize(4, __value)
        }
      };
      
      {
        val __value = dbName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(5, __value)
        }
      };
      
      {
        val __value = collectionName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(6, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      base.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      role.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      grantor.foreach { __v =>
        val __m = __v
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      {
        val __v = `type`.value
        if (__v != 0) {
          _output__.writeEnum(4, __v)
        }
      };
      {
        val __v = dbName
        if (!__v.isEmpty) {
          _output__.writeString(5, __v)
        }
      };
      {
        val __v = collectionName
        if (!__v.isEmpty) {
          _output__.writeString(6, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def getBase: io.milvus.grpc.common.MsgBase = base.getOrElse(io.milvus.grpc.common.MsgBase.defaultInstance)
    def clearBase: OperatePrivilegeV2Request = copy(base = _root_.scala.None)
    def withBase(__v: io.milvus.grpc.common.MsgBase): OperatePrivilegeV2Request = copy(base = Option(__v))
    def getRole: io.milvus.grpc.milvus.RoleEntity = role.getOrElse(io.milvus.grpc.milvus.RoleEntity.defaultInstance)
    def clearRole: OperatePrivilegeV2Request = copy(role = _root_.scala.None)
    def withRole(__v: io.milvus.grpc.milvus.RoleEntity): OperatePrivilegeV2Request = copy(role = Option(__v))
    def getGrantor: io.milvus.grpc.milvus.GrantorEntity = grantor.getOrElse(io.milvus.grpc.milvus.GrantorEntity.defaultInstance)
    def clearGrantor: OperatePrivilegeV2Request = copy(grantor = _root_.scala.None)
    def withGrantor(__v: io.milvus.grpc.milvus.GrantorEntity): OperatePrivilegeV2Request = copy(grantor = Option(__v))
    def withType(__v: io.milvus.grpc.milvus.OperatePrivilegeType): OperatePrivilegeV2Request = copy(`type` = __v)
    def withDbName(__v: _root_.scala.Predef.String): OperatePrivilegeV2Request = copy(dbName = __v)
    def withCollectionName(__v: _root_.scala.Predef.String): OperatePrivilegeV2Request = copy(collectionName = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => base.orNull
        case 2 => role.orNull
        case 3 => grantor.orNull
        case 4 => {
          val __t = `type`.javaValueDescriptor
          if (__t.getNumber() != 0) __t else null
        }
        case 5 => {
          val __t = dbName
          if (__t != "") __t else null
        }
        case 6 => {
          val __t = collectionName
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => base.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 2 => role.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => grantor.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 4 => _root_.scalapb.descriptors.PEnum(`type`.scalaValueDescriptor)
        case 5 => _root_.scalapb.descriptors.PString(dbName)
        case 6 => _root_.scalapb.descriptors.PString(collectionName)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: io.milvus.grpc.milvus.OperatePrivilegeV2Request.type = io.milvus.grpc.milvus.OperatePrivilegeV2Request
    // @@protoc_insertion_point(GeneratedMessage[milvus.proto.milvus.OperatePrivilegeV2Request])
}

object OperatePrivilegeV2Request extends scalapb.GeneratedMessageCompanion[io.milvus.grpc.milvus.OperatePrivilegeV2Request] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[io.milvus.grpc.milvus.OperatePrivilegeV2Request] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): io.milvus.grpc.milvus.OperatePrivilegeV2Request = {
    var __base: _root_.scala.Option[io.milvus.grpc.common.MsgBase] = _root_.scala.None
    var __role: _root_.scala.Option[io.milvus.grpc.milvus.RoleEntity] = _root_.scala.None
    var __grantor: _root_.scala.Option[io.milvus.grpc.milvus.GrantorEntity] = _root_.scala.None
    var __type: io.milvus.grpc.milvus.OperatePrivilegeType = io.milvus.grpc.milvus.OperatePrivilegeType.Grant
    var __dbName: _root_.scala.Predef.String = ""
    var __collectionName: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __base = _root_.scala.Option(__base.fold(_root_.scalapb.LiteParser.readMessage[io.milvus.grpc.common.MsgBase](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 18 =>
          __role = _root_.scala.Option(__role.fold(_root_.scalapb.LiteParser.readMessage[io.milvus.grpc.milvus.RoleEntity](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 26 =>
          __grantor = _root_.scala.Option(__grantor.fold(_root_.scalapb.LiteParser.readMessage[io.milvus.grpc.milvus.GrantorEntity](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 32 =>
          __type = io.milvus.grpc.milvus.OperatePrivilegeType.fromValue(_input__.readEnum())
        case 42 =>
          __dbName = _input__.readStringRequireUtf8()
        case 50 =>
          __collectionName = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    io.milvus.grpc.milvus.OperatePrivilegeV2Request(
        base = __base,
        role = __role,
        grantor = __grantor,
        `type` = __type,
        dbName = __dbName,
        collectionName = __collectionName,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[io.milvus.grpc.milvus.OperatePrivilegeV2Request] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      io.milvus.grpc.milvus.OperatePrivilegeV2Request(
        base = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).flatMap(_.as[_root_.scala.Option[io.milvus.grpc.common.MsgBase]]),
        role = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[io.milvus.grpc.milvus.RoleEntity]]),
        grantor = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[_root_.scala.Option[io.milvus.grpc.milvus.GrantorEntity]]),
        `type` = io.milvus.grpc.milvus.OperatePrivilegeType.fromValue(__fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scalapb.descriptors.EnumValueDescriptor]).getOrElse(io.milvus.grpc.milvus.OperatePrivilegeType.Grant.scalaValueDescriptor).number),
        dbName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        collectionName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = io.milvus.grpc.milvus.MilvusProto.javaDescriptor.getMessageTypes().get(137)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = io.milvus.grpc.milvus.MilvusProto.scalaDescriptor.messages(137)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[?] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = io.milvus.grpc.common.MsgBase
      case 2 => __out = io.milvus.grpc.milvus.RoleEntity
      case 3 => __out = io.milvus.grpc.milvus.GrantorEntity
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = {
    (__fieldNumber: @_root_.scala.unchecked) match {
      case 4 => io.milvus.grpc.milvus.OperatePrivilegeType
    }
  }
  lazy val defaultInstance = io.milvus.grpc.milvus.OperatePrivilegeV2Request(
    base = _root_.scala.None,
    role = _root_.scala.None,
    grantor = _root_.scala.None,
    `type` = io.milvus.grpc.milvus.OperatePrivilegeType.Grant,
    dbName = "",
    collectionName = ""
  )
  implicit class OperatePrivilegeV2RequestLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, io.milvus.grpc.milvus.OperatePrivilegeV2Request]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, io.milvus.grpc.milvus.OperatePrivilegeV2Request](_l) {
    def base: _root_.scalapb.lenses.Lens[UpperPB, io.milvus.grpc.common.MsgBase] = field(_.getBase)((c_, f_) => c_.copy(base = _root_.scala.Option(f_)))
    def optionalBase: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[io.milvus.grpc.common.MsgBase]] = field(_.base)((c_, f_) => c_.copy(base = f_))
    def role: _root_.scalapb.lenses.Lens[UpperPB, io.milvus.grpc.milvus.RoleEntity] = field(_.getRole)((c_, f_) => c_.copy(role = _root_.scala.Option(f_)))
    def optionalRole: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[io.milvus.grpc.milvus.RoleEntity]] = field(_.role)((c_, f_) => c_.copy(role = f_))
    def grantor: _root_.scalapb.lenses.Lens[UpperPB, io.milvus.grpc.milvus.GrantorEntity] = field(_.getGrantor)((c_, f_) => c_.copy(grantor = _root_.scala.Option(f_)))
    def optionalGrantor: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[io.milvus.grpc.milvus.GrantorEntity]] = field(_.grantor)((c_, f_) => c_.copy(grantor = f_))
    def `type`: _root_.scalapb.lenses.Lens[UpperPB, io.milvus.grpc.milvus.OperatePrivilegeType] = field(_.`type`)((c_, f_) => c_.copy(`type` = f_))
    def dbName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.dbName)((c_, f_) => c_.copy(dbName = f_))
    def collectionName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.collectionName)((c_, f_) => c_.copy(collectionName = f_))
  }
  final val BASE_FIELD_NUMBER = 1
  final val ROLE_FIELD_NUMBER = 2
  final val GRANTOR_FIELD_NUMBER = 3
  final val TYPE_FIELD_NUMBER = 4
  final val DB_NAME_FIELD_NUMBER = 5
  final val COLLECTION_NAME_FIELD_NUMBER = 6
  def of(
    base: _root_.scala.Option[io.milvus.grpc.common.MsgBase],
    role: _root_.scala.Option[io.milvus.grpc.milvus.RoleEntity],
    grantor: _root_.scala.Option[io.milvus.grpc.milvus.GrantorEntity],
    `type`: io.milvus.grpc.milvus.OperatePrivilegeType,
    dbName: _root_.scala.Predef.String,
    collectionName: _root_.scala.Predef.String
  ): _root_.io.milvus.grpc.milvus.OperatePrivilegeV2Request = _root_.io.milvus.grpc.milvus.OperatePrivilegeV2Request(
    base,
    role,
    grantor,
    `type`,
    dbName,
    collectionName
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[milvus.proto.milvus.OperatePrivilegeV2Request])
}
