// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.milvus.grpc.common

sealed abstract class CompactionState(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = io.milvus.grpc.common.CompactionState
  type RecognizedType = io.milvus.grpc.common.CompactionState.Recognized
  def isUndefiedState: _root_.scala.Boolean = false
  def isExecuting: _root_.scala.Boolean = false
  def isCompleted: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[CompactionState] = io.milvus.grpc.common.CompactionState
  final def asRecognized: _root_.scala.Option[io.milvus.grpc.common.CompactionState.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[io.milvus.grpc.common.CompactionState.Recognized])
}

object CompactionState extends _root_.scalapb.GeneratedEnumCompanion[CompactionState] {
  sealed trait Recognized extends CompactionState
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[CompactionState] = this
  
  @SerialVersionUID(0L)
  case object UndefiedState extends CompactionState(0) with CompactionState.Recognized {
    val index = 0
    val name = "UndefiedState"
    override def isUndefiedState: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Executing extends CompactionState(1) with CompactionState.Recognized {
    val index = 1
    val name = "Executing"
    override def isExecuting: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Completed extends CompactionState(2) with CompactionState.Recognized {
    val index = 2
    val name = "Completed"
    override def isCompleted: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends CompactionState(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(UndefiedState, Executing, Completed)
  def fromValue(__value: _root_.scala.Int): CompactionState = __value match {
    case 0 => UndefiedState
    case 1 => Executing
    case 2 => Completed
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = io.milvus.grpc.common.CommonProto.javaDescriptor.getEnumTypes().get(7)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = io.milvus.grpc.common.CommonProto.scalaDescriptor.enums(7)
}