// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.milvus.grpc.common

sealed abstract class MsgType(val value: _root_.scala.Int) extends _root_.scalapb.GeneratedEnum {
  type EnumType = io.milvus.grpc.common.MsgType
  type RecognizedType = io.milvus.grpc.common.MsgType.Recognized
  def isUndefined: _root_.scala.Boolean = false
  def isCreateCollection: _root_.scala.Boolean = false
  def isDropCollection: _root_.scala.Boolean = false
  def isHasCollection: _root_.scala.Boolean = false
  def isDescribeCollection: _root_.scala.Boolean = false
  def isShowCollections: _root_.scala.Boolean = false
  def isGetSystemConfigs: _root_.scala.Boolean = false
  def isLoadCollection: _root_.scala.Boolean = false
  def isReleaseCollection: _root_.scala.Boolean = false
  def isCreateAlias: _root_.scala.Boolean = false
  def isDropAlias: _root_.scala.Boolean = false
  def isAlterAlias: _root_.scala.Boolean = false
  def isAlterCollection: _root_.scala.Boolean = false
  def isRenameCollection: _root_.scala.Boolean = false
  def isDescribeAlias: _root_.scala.Boolean = false
  def isListAliases: _root_.scala.Boolean = false
  def isAlterCollectionField: _root_.scala.Boolean = false
  def isCreatePartition: _root_.scala.Boolean = false
  def isDropPartition: _root_.scala.Boolean = false
  def isHasPartition: _root_.scala.Boolean = false
  def isDescribePartition: _root_.scala.Boolean = false
  def isShowPartitions: _root_.scala.Boolean = false
  def isLoadPartitions: _root_.scala.Boolean = false
  def isReleasePartitions: _root_.scala.Boolean = false
  def isShowSegments: _root_.scala.Boolean = false
  def isDescribeSegment: _root_.scala.Boolean = false
  def isLoadSegments: _root_.scala.Boolean = false
  def isReleaseSegments: _root_.scala.Boolean = false
  def isHandoffSegments: _root_.scala.Boolean = false
  def isLoadBalanceSegments: _root_.scala.Boolean = false
  def isDescribeSegments: _root_.scala.Boolean = false
  def isFederListIndexedSegment: _root_.scala.Boolean = false
  def isFederDescribeSegmentIndexData: _root_.scala.Boolean = false
  def isCreateIndex: _root_.scala.Boolean = false
  def isDescribeIndex: _root_.scala.Boolean = false
  def isDropIndex: _root_.scala.Boolean = false
  def isGetIndexStatistics: _root_.scala.Boolean = false
  def isAlterIndex: _root_.scala.Boolean = false
  def isInsert: _root_.scala.Boolean = false
  def isDelete: _root_.scala.Boolean = false
  def isFlush: _root_.scala.Boolean = false
  def isResendSegmentStats: _root_.scala.Boolean = false
  def isUpsert: _root_.scala.Boolean = false
  def isManualFlush: _root_.scala.Boolean = false
  def isFlushSegment: _root_.scala.Boolean = false
  def isCreateSegment: _root_.scala.Boolean = false
  def isImport: _root_.scala.Boolean = false
  def isSearch: _root_.scala.Boolean = false
  def isSearchResult: _root_.scala.Boolean = false
  def isGetIndexState: _root_.scala.Boolean = false
  def isGetIndexBuildProgress: _root_.scala.Boolean = false
  def isGetCollectionStatistics: _root_.scala.Boolean = false
  def isGetPartitionStatistics: _root_.scala.Boolean = false
  def isRetrieve: _root_.scala.Boolean = false
  def isRetrieveResult: _root_.scala.Boolean = false
  def isWatchDmChannels: _root_.scala.Boolean = false
  def isRemoveDmChannels: _root_.scala.Boolean = false
  def isWatchQueryChannels: _root_.scala.Boolean = false
  def isRemoveQueryChannels: _root_.scala.Boolean = false
  def isSealedSegmentsChangeInfo: _root_.scala.Boolean = false
  def isWatchDeltaChannels: _root_.scala.Boolean = false
  def isGetShardLeaders: _root_.scala.Boolean = false
  def isGetReplicas: _root_.scala.Boolean = false
  def isUnsubDmChannel: _root_.scala.Boolean = false
  def isGetDistribution: _root_.scala.Boolean = false
  def isSyncDistribution: _root_.scala.Boolean = false
  def isRunAnalyzer: _root_.scala.Boolean = false
  def isSegmentInfo: _root_.scala.Boolean = false
  def isSystemInfo: _root_.scala.Boolean = false
  def isGetRecoveryInfo: _root_.scala.Boolean = false
  def isGetSegmentState: _root_.scala.Boolean = false
  def isTimeTick: _root_.scala.Boolean = false
  def isQueryNodeStats: _root_.scala.Boolean = false
  def isLoadIndex: _root_.scala.Boolean = false
  def isRequestId: _root_.scala.Boolean = false
  def isRequestTso: _root_.scala.Boolean = false
  def isAllocateSegment: _root_.scala.Boolean = false
  def isSegmentStatistics: _root_.scala.Boolean = false
  def isSegmentFlushDone: _root_.scala.Boolean = false
  def isDataNodeTt: _root_.scala.Boolean = false
  def isConnect: _root_.scala.Boolean = false
  def isListClientInfos: _root_.scala.Boolean = false
  def isAllocTimestamp: _root_.scala.Boolean = false
  def isReplicate: _root_.scala.Boolean = false
  def isCreateCredential: _root_.scala.Boolean = false
  def isGetCredential: _root_.scala.Boolean = false
  def isDeleteCredential: _root_.scala.Boolean = false
  def isUpdateCredential: _root_.scala.Boolean = false
  def isListCredUsernames: _root_.scala.Boolean = false
  def isCreateRole: _root_.scala.Boolean = false
  def isDropRole: _root_.scala.Boolean = false
  def isOperateUserRole: _root_.scala.Boolean = false
  def isSelectRole: _root_.scala.Boolean = false
  def isSelectUser: _root_.scala.Boolean = false
  def isSelectResource: _root_.scala.Boolean = false
  def isOperatePrivilege: _root_.scala.Boolean = false
  def isSelectGrant: _root_.scala.Boolean = false
  def isRefreshPolicyInfoCache: _root_.scala.Boolean = false
  def isListPolicy: _root_.scala.Boolean = false
  def isCreatePrivilegeGroup: _root_.scala.Boolean = false
  def isDropPrivilegeGroup: _root_.scala.Boolean = false
  def isListPrivilegeGroups: _root_.scala.Boolean = false
  def isOperatePrivilegeGroup: _root_.scala.Boolean = false
  def isOperatePrivilegeV2: _root_.scala.Boolean = false
  def isCreateResourceGroup: _root_.scala.Boolean = false
  def isDropResourceGroup: _root_.scala.Boolean = false
  def isListResourceGroups: _root_.scala.Boolean = false
  def isDescribeResourceGroup: _root_.scala.Boolean = false
  def isTransferNode: _root_.scala.Boolean = false
  def isTransferReplica: _root_.scala.Boolean = false
  def isUpdateResourceGroups: _root_.scala.Boolean = false
  def isCreateDatabase: _root_.scala.Boolean = false
  def isDropDatabase: _root_.scala.Boolean = false
  def isListDatabases: _root_.scala.Boolean = false
  def isAlterDatabase: _root_.scala.Boolean = false
  def isDescribeDatabase: _root_.scala.Boolean = false
  def isAddCollectionField: _root_.scala.Boolean = false
  def companion: _root_.scalapb.GeneratedEnumCompanion[MsgType] = io.milvus.grpc.common.MsgType
  final def asRecognized: _root_.scala.Option[io.milvus.grpc.common.MsgType.Recognized] = if (isUnrecognized) _root_.scala.None else _root_.scala.Some(this.asInstanceOf[io.milvus.grpc.common.MsgType.Recognized])
}

object MsgType extends _root_.scalapb.GeneratedEnumCompanion[MsgType] {
  sealed trait Recognized extends MsgType
  implicit def enumCompanion: _root_.scalapb.GeneratedEnumCompanion[MsgType] = this
  
  @SerialVersionUID(0L)
  case object Undefined extends MsgType(0) with MsgType.Recognized {
    val index = 0
    val name = "Undefined"
    override def isUndefined: _root_.scala.Boolean = true
  }
  
  /** DEFINITION REQUESTS: COLLECTION 
    */
  @SerialVersionUID(0L)
  case object CreateCollection extends MsgType(100) with MsgType.Recognized {
    val index = 1
    val name = "CreateCollection"
    override def isCreateCollection: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DropCollection extends MsgType(101) with MsgType.Recognized {
    val index = 2
    val name = "DropCollection"
    override def isDropCollection: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object HasCollection extends MsgType(102) with MsgType.Recognized {
    val index = 3
    val name = "HasCollection"
    override def isHasCollection: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DescribeCollection extends MsgType(103) with MsgType.Recognized {
    val index = 4
    val name = "DescribeCollection"
    override def isDescribeCollection: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ShowCollections extends MsgType(104) with MsgType.Recognized {
    val index = 5
    val name = "ShowCollections"
    override def isShowCollections: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GetSystemConfigs extends MsgType(105) with MsgType.Recognized {
    val index = 6
    val name = "GetSystemConfigs"
    override def isGetSystemConfigs: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object LoadCollection extends MsgType(106) with MsgType.Recognized {
    val index = 7
    val name = "LoadCollection"
    override def isLoadCollection: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ReleaseCollection extends MsgType(107) with MsgType.Recognized {
    val index = 8
    val name = "ReleaseCollection"
    override def isReleaseCollection: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object CreateAlias extends MsgType(108) with MsgType.Recognized {
    val index = 9
    val name = "CreateAlias"
    override def isCreateAlias: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DropAlias extends MsgType(109) with MsgType.Recognized {
    val index = 10
    val name = "DropAlias"
    override def isDropAlias: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object AlterAlias extends MsgType(110) with MsgType.Recognized {
    val index = 11
    val name = "AlterAlias"
    override def isAlterAlias: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object AlterCollection extends MsgType(111) with MsgType.Recognized {
    val index = 12
    val name = "AlterCollection"
    override def isAlterCollection: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RenameCollection extends MsgType(112) with MsgType.Recognized {
    val index = 13
    val name = "RenameCollection"
    override def isRenameCollection: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DescribeAlias extends MsgType(113) with MsgType.Recognized {
    val index = 14
    val name = "DescribeAlias"
    override def isDescribeAlias: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ListAliases extends MsgType(114) with MsgType.Recognized {
    val index = 15
    val name = "ListAliases"
    override def isListAliases: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object AlterCollectionField extends MsgType(115) with MsgType.Recognized {
    val index = 16
    val name = "AlterCollectionField"
    override def isAlterCollectionField: _root_.scala.Boolean = true
  }
  
  /** DEFINITION REQUESTS: PARTITION 
    */
  @SerialVersionUID(0L)
  case object CreatePartition extends MsgType(200) with MsgType.Recognized {
    val index = 17
    val name = "CreatePartition"
    override def isCreatePartition: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DropPartition extends MsgType(201) with MsgType.Recognized {
    val index = 18
    val name = "DropPartition"
    override def isDropPartition: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object HasPartition extends MsgType(202) with MsgType.Recognized {
    val index = 19
    val name = "HasPartition"
    override def isHasPartition: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DescribePartition extends MsgType(203) with MsgType.Recognized {
    val index = 20
    val name = "DescribePartition"
    override def isDescribePartition: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ShowPartitions extends MsgType(204) with MsgType.Recognized {
    val index = 21
    val name = "ShowPartitions"
    override def isShowPartitions: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object LoadPartitions extends MsgType(205) with MsgType.Recognized {
    val index = 22
    val name = "LoadPartitions"
    override def isLoadPartitions: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ReleasePartitions extends MsgType(206) with MsgType.Recognized {
    val index = 23
    val name = "ReleasePartitions"
    override def isReleasePartitions: _root_.scala.Boolean = true
  }
  
  /** DEFINE REQUESTS: SEGMENT 
    */
  @SerialVersionUID(0L)
  case object ShowSegments extends MsgType(250) with MsgType.Recognized {
    val index = 24
    val name = "ShowSegments"
    override def isShowSegments: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DescribeSegment extends MsgType(251) with MsgType.Recognized {
    val index = 25
    val name = "DescribeSegment"
    override def isDescribeSegment: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object LoadSegments extends MsgType(252) with MsgType.Recognized {
    val index = 26
    val name = "LoadSegments"
    override def isLoadSegments: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ReleaseSegments extends MsgType(253) with MsgType.Recognized {
    val index = 27
    val name = "ReleaseSegments"
    override def isReleaseSegments: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object HandoffSegments extends MsgType(254) with MsgType.Recognized {
    val index = 28
    val name = "HandoffSegments"
    override def isHandoffSegments: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object LoadBalanceSegments extends MsgType(255) with MsgType.Recognized {
    val index = 29
    val name = "LoadBalanceSegments"
    override def isLoadBalanceSegments: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DescribeSegments extends MsgType(256) with MsgType.Recognized {
    val index = 30
    val name = "DescribeSegments"
    override def isDescribeSegments: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object FederListIndexedSegment extends MsgType(257) with MsgType.Recognized {
    val index = 31
    val name = "FederListIndexedSegment"
    override def isFederListIndexedSegment: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object FederDescribeSegmentIndexData extends MsgType(258) with MsgType.Recognized {
    val index = 32
    val name = "FederDescribeSegmentIndexData"
    override def isFederDescribeSegmentIndexData: _root_.scala.Boolean = true
  }
  
  /** DEFINITION REQUESTS: INDEX 
    */
  @SerialVersionUID(0L)
  case object CreateIndex extends MsgType(300) with MsgType.Recognized {
    val index = 33
    val name = "CreateIndex"
    override def isCreateIndex: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DescribeIndex extends MsgType(301) with MsgType.Recognized {
    val index = 34
    val name = "DescribeIndex"
    override def isDescribeIndex: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DropIndex extends MsgType(302) with MsgType.Recognized {
    val index = 35
    val name = "DropIndex"
    override def isDropIndex: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GetIndexStatistics extends MsgType(303) with MsgType.Recognized {
    val index = 36
    val name = "GetIndexStatistics"
    override def isGetIndexStatistics: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object AlterIndex extends MsgType(304) with MsgType.Recognized {
    val index = 37
    val name = "AlterIndex"
    override def isAlterIndex: _root_.scala.Boolean = true
  }
  
  /** MANIPULATION REQUESTS 
    */
  @SerialVersionUID(0L)
  case object Insert extends MsgType(400) with MsgType.Recognized {
    val index = 38
    val name = "Insert"
    override def isInsert: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Delete extends MsgType(401) with MsgType.Recognized {
    val index = 39
    val name = "Delete"
    override def isDelete: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Flush extends MsgType(402) with MsgType.Recognized {
    val index = 40
    val name = "Flush"
    override def isFlush: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ResendSegmentStats extends MsgType(403) with MsgType.Recognized {
    val index = 41
    val name = "ResendSegmentStats"
    override def isResendSegmentStats: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Upsert extends MsgType(404) with MsgType.Recognized {
    val index = 42
    val name = "Upsert"
    override def isUpsert: _root_.scala.Boolean = true
  }
  
  /** streaming service new msg type for internal usage compatible
    */
  @SerialVersionUID(0L)
  case object ManualFlush extends MsgType(405) with MsgType.Recognized {
    val index = 43
    val name = "ManualFlush"
    override def isManualFlush: _root_.scala.Boolean = true
  }
  
  /** streaming service new msg type for internal usage compatible
    */
  @SerialVersionUID(0L)
  case object FlushSegment extends MsgType(406) with MsgType.Recognized {
    val index = 44
    val name = "FlushSegment"
    override def isFlushSegment: _root_.scala.Boolean = true
  }
  
  /** streaming service new msg type for internal usage compatible
    */
  @SerialVersionUID(0L)
  case object CreateSegment extends MsgType(407) with MsgType.Recognized {
    val index = 45
    val name = "CreateSegment"
    override def isCreateSegment: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Import extends MsgType(408) with MsgType.Recognized {
    val index = 46
    val name = "Import"
    override def isImport: _root_.scala.Boolean = true
  }
  
  /** QUERY 
    */
  @SerialVersionUID(0L)
  case object Search extends MsgType(500) with MsgType.Recognized {
    val index = 47
    val name = "Search"
    override def isSearch: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SearchResult extends MsgType(501) with MsgType.Recognized {
    val index = 48
    val name = "SearchResult"
    override def isSearchResult: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GetIndexState extends MsgType(502) with MsgType.Recognized {
    val index = 49
    val name = "GetIndexState"
    override def isGetIndexState: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GetIndexBuildProgress extends MsgType(503) with MsgType.Recognized {
    val index = 50
    val name = "GetIndexBuildProgress"
    override def isGetIndexBuildProgress: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GetCollectionStatistics extends MsgType(504) with MsgType.Recognized {
    val index = 51
    val name = "GetCollectionStatistics"
    override def isGetCollectionStatistics: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GetPartitionStatistics extends MsgType(505) with MsgType.Recognized {
    val index = 52
    val name = "GetPartitionStatistics"
    override def isGetPartitionStatistics: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Retrieve extends MsgType(506) with MsgType.Recognized {
    val index = 53
    val name = "Retrieve"
    override def isRetrieve: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RetrieveResult extends MsgType(507) with MsgType.Recognized {
    val index = 54
    val name = "RetrieveResult"
    override def isRetrieveResult: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object WatchDmChannels extends MsgType(508) with MsgType.Recognized {
    val index = 55
    val name = "WatchDmChannels"
    override def isWatchDmChannels: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RemoveDmChannels extends MsgType(509) with MsgType.Recognized {
    val index = 56
    val name = "RemoveDmChannels"
    override def isRemoveDmChannels: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object WatchQueryChannels extends MsgType(510) with MsgType.Recognized {
    val index = 57
    val name = "WatchQueryChannels"
    override def isWatchQueryChannels: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RemoveQueryChannels extends MsgType(511) with MsgType.Recognized {
    val index = 58
    val name = "RemoveQueryChannels"
    override def isRemoveQueryChannels: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SealedSegmentsChangeInfo extends MsgType(512) with MsgType.Recognized {
    val index = 59
    val name = "SealedSegmentsChangeInfo"
    override def isSealedSegmentsChangeInfo: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object WatchDeltaChannels extends MsgType(513) with MsgType.Recognized {
    val index = 60
    val name = "WatchDeltaChannels"
    override def isWatchDeltaChannels: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GetShardLeaders extends MsgType(514) with MsgType.Recognized {
    val index = 61
    val name = "GetShardLeaders"
    override def isGetShardLeaders: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GetReplicas extends MsgType(515) with MsgType.Recognized {
    val index = 62
    val name = "GetReplicas"
    override def isGetReplicas: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object UnsubDmChannel extends MsgType(516) with MsgType.Recognized {
    val index = 63
    val name = "UnsubDmChannel"
    override def isUnsubDmChannel: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GetDistribution extends MsgType(517) with MsgType.Recognized {
    val index = 64
    val name = "GetDistribution"
    override def isGetDistribution: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SyncDistribution extends MsgType(518) with MsgType.Recognized {
    val index = 65
    val name = "SyncDistribution"
    override def isSyncDistribution: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RunAnalyzer extends MsgType(519) with MsgType.Recognized {
    val index = 66
    val name = "RunAnalyzer"
    override def isRunAnalyzer: _root_.scala.Boolean = true
  }
  
  /** DATA SERVICE 
    */
  @SerialVersionUID(0L)
  case object SegmentInfo extends MsgType(600) with MsgType.Recognized {
    val index = 67
    val name = "SegmentInfo"
    override def isSegmentInfo: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SystemInfo extends MsgType(601) with MsgType.Recognized {
    val index = 68
    val name = "SystemInfo"
    override def isSystemInfo: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GetRecoveryInfo extends MsgType(602) with MsgType.Recognized {
    val index = 69
    val name = "GetRecoveryInfo"
    override def isGetRecoveryInfo: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GetSegmentState extends MsgType(603) with MsgType.Recognized {
    val index = 70
    val name = "GetSegmentState"
    override def isGetSegmentState: _root_.scala.Boolean = true
  }
  
  /** SYSTEM CONTROL 
    */
  @SerialVersionUID(0L)
  case object TimeTick extends MsgType(1200) with MsgType.Recognized {
    val index = 71
    val name = "TimeTick"
    override def isTimeTick: _root_.scala.Boolean = true
  }
  
  /** GOOSE TODO: Remove kQueryNodeStats
    */
  @SerialVersionUID(0L)
  case object QueryNodeStats extends MsgType(1201) with MsgType.Recognized {
    val index = 72
    val name = "QueryNodeStats"
    override def isQueryNodeStats: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object LoadIndex extends MsgType(1202) with MsgType.Recognized {
    val index = 73
    val name = "LoadIndex"
    override def isLoadIndex: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RequestID extends MsgType(1203) with MsgType.Recognized {
    val index = 74
    val name = "RequestID"
    override def isRequestId: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RequestTSO extends MsgType(1204) with MsgType.Recognized {
    val index = 75
    val name = "RequestTSO"
    override def isRequestTso: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object AllocateSegment extends MsgType(1205) with MsgType.Recognized {
    val index = 76
    val name = "AllocateSegment"
    override def isAllocateSegment: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SegmentStatistics extends MsgType(1206) with MsgType.Recognized {
    val index = 77
    val name = "SegmentStatistics"
    override def isSegmentStatistics: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SegmentFlushDone extends MsgType(1207) with MsgType.Recognized {
    val index = 78
    val name = "SegmentFlushDone"
    override def isSegmentFlushDone: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DataNodeTt extends MsgType(1208) with MsgType.Recognized {
    val index = 79
    val name = "DataNodeTt"
    override def isDataNodeTt: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Connect extends MsgType(1209) with MsgType.Recognized {
    val index = 80
    val name = "Connect"
    override def isConnect: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ListClientInfos extends MsgType(1210) with MsgType.Recognized {
    val index = 81
    val name = "ListClientInfos"
    override def isListClientInfos: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object AllocTimestamp extends MsgType(1211) with MsgType.Recognized {
    val index = 82
    val name = "AllocTimestamp"
    override def isAllocTimestamp: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Replicate extends MsgType(1212) with MsgType.Recognized {
    val index = 83
    val name = "Replicate"
    override def isReplicate: _root_.scala.Boolean = true
  }
  
  /** Credential 
    */
  @SerialVersionUID(0L)
  case object CreateCredential extends MsgType(1500) with MsgType.Recognized {
    val index = 84
    val name = "CreateCredential"
    override def isCreateCredential: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object GetCredential extends MsgType(1501) with MsgType.Recognized {
    val index = 85
    val name = "GetCredential"
    override def isGetCredential: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DeleteCredential extends MsgType(1502) with MsgType.Recognized {
    val index = 86
    val name = "DeleteCredential"
    override def isDeleteCredential: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object UpdateCredential extends MsgType(1503) with MsgType.Recognized {
    val index = 87
    val name = "UpdateCredential"
    override def isUpdateCredential: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ListCredUsernames extends MsgType(1504) with MsgType.Recognized {
    val index = 88
    val name = "ListCredUsernames"
    override def isListCredUsernames: _root_.scala.Boolean = true
  }
  
  /** RBAC 
    */
  @SerialVersionUID(0L)
  case object CreateRole extends MsgType(1600) with MsgType.Recognized {
    val index = 89
    val name = "CreateRole"
    override def isCreateRole: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DropRole extends MsgType(1601) with MsgType.Recognized {
    val index = 90
    val name = "DropRole"
    override def isDropRole: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object OperateUserRole extends MsgType(1602) with MsgType.Recognized {
    val index = 91
    val name = "OperateUserRole"
    override def isOperateUserRole: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SelectRole extends MsgType(1603) with MsgType.Recognized {
    val index = 92
    val name = "SelectRole"
    override def isSelectRole: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SelectUser extends MsgType(1604) with MsgType.Recognized {
    val index = 93
    val name = "SelectUser"
    override def isSelectUser: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SelectResource extends MsgType(1605) with MsgType.Recognized {
    val index = 94
    val name = "SelectResource"
    override def isSelectResource: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object OperatePrivilege extends MsgType(1606) with MsgType.Recognized {
    val index = 95
    val name = "OperatePrivilege"
    override def isOperatePrivilege: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object SelectGrant extends MsgType(1607) with MsgType.Recognized {
    val index = 96
    val name = "SelectGrant"
    override def isSelectGrant: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object RefreshPolicyInfoCache extends MsgType(1608) with MsgType.Recognized {
    val index = 97
    val name = "RefreshPolicyInfoCache"
    override def isRefreshPolicyInfoCache: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ListPolicy extends MsgType(1609) with MsgType.Recognized {
    val index = 98
    val name = "ListPolicy"
    override def isListPolicy: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object CreatePrivilegeGroup extends MsgType(1610) with MsgType.Recognized {
    val index = 99
    val name = "CreatePrivilegeGroup"
    override def isCreatePrivilegeGroup: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DropPrivilegeGroup extends MsgType(1611) with MsgType.Recognized {
    val index = 100
    val name = "DropPrivilegeGroup"
    override def isDropPrivilegeGroup: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ListPrivilegeGroups extends MsgType(1612) with MsgType.Recognized {
    val index = 101
    val name = "ListPrivilegeGroups"
    override def isListPrivilegeGroups: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object OperatePrivilegeGroup extends MsgType(1613) with MsgType.Recognized {
    val index = 102
    val name = "OperatePrivilegeGroup"
    override def isOperatePrivilegeGroup: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object OperatePrivilegeV2 extends MsgType(1614) with MsgType.Recognized {
    val index = 103
    val name = "OperatePrivilegeV2"
    override def isOperatePrivilegeV2: _root_.scala.Boolean = true
  }
  
  /** Resource group 
    */
  @SerialVersionUID(0L)
  case object CreateResourceGroup extends MsgType(1700) with MsgType.Recognized {
    val index = 104
    val name = "CreateResourceGroup"
    override def isCreateResourceGroup: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DropResourceGroup extends MsgType(1701) with MsgType.Recognized {
    val index = 105
    val name = "DropResourceGroup"
    override def isDropResourceGroup: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ListResourceGroups extends MsgType(1702) with MsgType.Recognized {
    val index = 106
    val name = "ListResourceGroups"
    override def isListResourceGroups: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DescribeResourceGroup extends MsgType(1703) with MsgType.Recognized {
    val index = 107
    val name = "DescribeResourceGroup"
    override def isDescribeResourceGroup: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object TransferNode extends MsgType(1704) with MsgType.Recognized {
    val index = 108
    val name = "TransferNode"
    override def isTransferNode: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object TransferReplica extends MsgType(1705) with MsgType.Recognized {
    val index = 109
    val name = "TransferReplica"
    override def isTransferReplica: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object UpdateResourceGroups extends MsgType(1706) with MsgType.Recognized {
    val index = 110
    val name = "UpdateResourceGroups"
    override def isUpdateResourceGroups: _root_.scala.Boolean = true
  }
  
  /** Database group 
    */
  @SerialVersionUID(0L)
  case object CreateDatabase extends MsgType(1801) with MsgType.Recognized {
    val index = 111
    val name = "CreateDatabase"
    override def isCreateDatabase: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DropDatabase extends MsgType(1802) with MsgType.Recognized {
    val index = 112
    val name = "DropDatabase"
    override def isDropDatabase: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object ListDatabases extends MsgType(1803) with MsgType.Recognized {
    val index = 113
    val name = "ListDatabases"
    override def isListDatabases: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object AlterDatabase extends MsgType(1804) with MsgType.Recognized {
    val index = 114
    val name = "AlterDatabase"
    override def isAlterDatabase: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DescribeDatabase extends MsgType(1805) with MsgType.Recognized {
    val index = 115
    val name = "DescribeDatabase"
    override def isDescribeDatabase: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object AddCollectionField extends MsgType(1900) with MsgType.Recognized {
    val index = 116
    val name = "AddCollectionField"
    override def isAddCollectionField: _root_.scala.Boolean = true
  }
  
  @SerialVersionUID(0L)
  final case class Unrecognized(unrecognizedValue: _root_.scala.Int) extends MsgType(unrecognizedValue) with _root_.scalapb.UnrecognizedEnum
  lazy val values: scala.collection.immutable.Seq[ValueType] = scala.collection.immutable.Seq(Undefined, CreateCollection, DropCollection, HasCollection, DescribeCollection, ShowCollections, GetSystemConfigs, LoadCollection, ReleaseCollection, CreateAlias, DropAlias, AlterAlias, AlterCollection, RenameCollection, DescribeAlias, ListAliases, AlterCollectionField, CreatePartition, DropPartition, HasPartition, DescribePartition, ShowPartitions, LoadPartitions, ReleasePartitions, ShowSegments, DescribeSegment, LoadSegments, ReleaseSegments, HandoffSegments, LoadBalanceSegments, DescribeSegments, FederListIndexedSegment, FederDescribeSegmentIndexData, CreateIndex, DescribeIndex, DropIndex, GetIndexStatistics, AlterIndex, Insert, Delete, Flush, ResendSegmentStats, Upsert, ManualFlush, FlushSegment, CreateSegment, Import, Search, SearchResult, GetIndexState, GetIndexBuildProgress, GetCollectionStatistics, GetPartitionStatistics, Retrieve, RetrieveResult, WatchDmChannels, RemoveDmChannels, WatchQueryChannels, RemoveQueryChannels, SealedSegmentsChangeInfo, WatchDeltaChannels, GetShardLeaders, GetReplicas, UnsubDmChannel, GetDistribution, SyncDistribution, RunAnalyzer, SegmentInfo, SystemInfo, GetRecoveryInfo, GetSegmentState, TimeTick, QueryNodeStats, LoadIndex, RequestID, RequestTSO, AllocateSegment, SegmentStatistics, SegmentFlushDone, DataNodeTt, Connect, ListClientInfos, AllocTimestamp, Replicate, CreateCredential, GetCredential, DeleteCredential, UpdateCredential, ListCredUsernames, CreateRole, DropRole, OperateUserRole, SelectRole, SelectUser, SelectResource, OperatePrivilege, SelectGrant, RefreshPolicyInfoCache, ListPolicy, CreatePrivilegeGroup, DropPrivilegeGroup, ListPrivilegeGroups, OperatePrivilegeGroup, OperatePrivilegeV2, CreateResourceGroup, DropResourceGroup, ListResourceGroups, DescribeResourceGroup, TransferNode, TransferReplica, UpdateResourceGroups, CreateDatabase, DropDatabase, ListDatabases, AlterDatabase, DescribeDatabase, AddCollectionField)
  def fromValue(__value: _root_.scala.Int): MsgType = __value match {
    case 0 => Undefined
    case 100 => CreateCollection
    case 101 => DropCollection
    case 102 => HasCollection
    case 103 => DescribeCollection
    case 104 => ShowCollections
    case 105 => GetSystemConfigs
    case 106 => LoadCollection
    case 107 => ReleaseCollection
    case 108 => CreateAlias
    case 109 => DropAlias
    case 110 => AlterAlias
    case 111 => AlterCollection
    case 112 => RenameCollection
    case 113 => DescribeAlias
    case 114 => ListAliases
    case 115 => AlterCollectionField
    case 200 => CreatePartition
    case 201 => DropPartition
    case 202 => HasPartition
    case 203 => DescribePartition
    case 204 => ShowPartitions
    case 205 => LoadPartitions
    case 206 => ReleasePartitions
    case 250 => ShowSegments
    case 251 => DescribeSegment
    case 252 => LoadSegments
    case 253 => ReleaseSegments
    case 254 => HandoffSegments
    case 255 => LoadBalanceSegments
    case 256 => DescribeSegments
    case 257 => FederListIndexedSegment
    case 258 => FederDescribeSegmentIndexData
    case 300 => CreateIndex
    case 301 => DescribeIndex
    case 302 => DropIndex
    case 303 => GetIndexStatistics
    case 304 => AlterIndex
    case 400 => Insert
    case 401 => Delete
    case 402 => Flush
    case 403 => ResendSegmentStats
    case 404 => Upsert
    case 405 => ManualFlush
    case 406 => FlushSegment
    case 407 => CreateSegment
    case 408 => Import
    case 500 => Search
    case 501 => SearchResult
    case 502 => GetIndexState
    case 503 => GetIndexBuildProgress
    case 504 => GetCollectionStatistics
    case 505 => GetPartitionStatistics
    case 506 => Retrieve
    case 507 => RetrieveResult
    case 508 => WatchDmChannels
    case 509 => RemoveDmChannels
    case 510 => WatchQueryChannels
    case 511 => RemoveQueryChannels
    case 512 => SealedSegmentsChangeInfo
    case 513 => WatchDeltaChannels
    case 514 => GetShardLeaders
    case 515 => GetReplicas
    case 516 => UnsubDmChannel
    case 517 => GetDistribution
    case 518 => SyncDistribution
    case 519 => RunAnalyzer
    case 600 => SegmentInfo
    case 601 => SystemInfo
    case 602 => GetRecoveryInfo
    case 603 => GetSegmentState
    case 1200 => TimeTick
    case 1201 => QueryNodeStats
    case 1202 => LoadIndex
    case 1203 => RequestID
    case 1204 => RequestTSO
    case 1205 => AllocateSegment
    case 1206 => SegmentStatistics
    case 1207 => SegmentFlushDone
    case 1208 => DataNodeTt
    case 1209 => Connect
    case 1210 => ListClientInfos
    case 1211 => AllocTimestamp
    case 1212 => Replicate
    case 1500 => CreateCredential
    case 1501 => GetCredential
    case 1502 => DeleteCredential
    case 1503 => UpdateCredential
    case 1504 => ListCredUsernames
    case 1600 => CreateRole
    case 1601 => DropRole
    case 1602 => OperateUserRole
    case 1603 => SelectRole
    case 1604 => SelectUser
    case 1605 => SelectResource
    case 1606 => OperatePrivilege
    case 1607 => SelectGrant
    case 1608 => RefreshPolicyInfoCache
    case 1609 => ListPolicy
    case 1610 => CreatePrivilegeGroup
    case 1611 => DropPrivilegeGroup
    case 1612 => ListPrivilegeGroups
    case 1613 => OperatePrivilegeGroup
    case 1614 => OperatePrivilegeV2
    case 1700 => CreateResourceGroup
    case 1701 => DropResourceGroup
    case 1702 => ListResourceGroups
    case 1703 => DescribeResourceGroup
    case 1704 => TransferNode
    case 1705 => TransferReplica
    case 1706 => UpdateResourceGroups
    case 1801 => CreateDatabase
    case 1802 => DropDatabase
    case 1803 => ListDatabases
    case 1804 => AlterDatabase
    case 1805 => DescribeDatabase
    case 1900 => AddCollectionField
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = io.milvus.grpc.common.CommonProto.javaDescriptor.getEnumTypes().get(5)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = io.milvus.grpc.common.CommonProto.scalaDescriptor.enums(5)
}