// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package milvus.proto.feder

import milvus.proto.feder

/** @param indexData
  *   data from knownwhere
  */
@SerialVersionUID(0L)
final case class SegmentIndexData(
    segmentID: _root_.scala.Long = 0L,
    indexData: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[SegmentIndexData] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = segmentID
        if (__value != 0L) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt64Size(1, __value)
        }
      };
      
      {
        val __value = indexData
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = segmentID
        if (__v != 0L) {
          _output__.writeInt64(1, __v)
        }
      };
      {
        val __v = indexData
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withSegmentID(__v: _root_.scala.Long): SegmentIndexData = copy(segmentID = __v)
    def withIndexData(__v: _root_.scala.Predef.String): SegmentIndexData = copy(indexData = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = segmentID
          if (__t != 0L) __t else null
        }
        case 2 => {
          val __t = indexData
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PLong(segmentID)
        case 2 => _root_.scalapb.descriptors.PString(indexData)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: SegmentIndexData.type = feder.SegmentIndexData
    // @@protoc_insertion_point(GeneratedMessage[milvus.proto.feder.SegmentIndexData])
}

object SegmentIndexData extends scalapb.GeneratedMessageCompanion[SegmentIndexData] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[SegmentIndexData] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): SegmentIndexData = {
    var __segmentID: _root_.scala.Long = 0L
    var __indexData: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __segmentID = _input__.readInt64()
        case 18 =>
          __indexData = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    SegmentIndexData(
        segmentID = __segmentID,
        indexData = __indexData,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[SegmentIndexData] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      SegmentIndexData(
        segmentID = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Long]).getOrElse(0L),
        indexData = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = FederProto.javaDescriptor.getMessageTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = feder.FederProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = SegmentIndexData(
    segmentID = 0L,
    indexData = ""
  )
  implicit class SegmentIndexDataLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, SegmentIndexData]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, SegmentIndexData](_l) {
    def segmentID: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Long] = field(_.segmentID)((c_, f_) => c_.copy(segmentID = f_))
    def indexData: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.indexData)((c_, f_) => c_.copy(indexData = f_))
  }
  final val SEGMENTID_FIELD_NUMBER = 1
  final val INDEX_DATA_FIELD_NUMBER = 2
  def of(
    segmentID: _root_.scala.Long,
    indexData: _root_.scala.Predef.String
  ): SegmentIndexData = SegmentIndexData(
    segmentID,
    indexData
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[milvus.proto.feder.SegmentIndexData])
}
