// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package io.milvus.grpc.rg

object RgProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    io.milvus.grpc.common.CommonProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]](
      io.milvus.grpc.rg.ResourceGroupLimit,
      io.milvus.grpc.rg.ResourceGroupTransfer,
      io.milvus.grpc.rg.ResourceGroupNodeFilter,
      io.milvus.grpc.rg.ResourceGroupConfig
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cg9taWx2dXMvcmcucHJvdG8SD21pbHZ1cy5wcm90by5yZxoTbWlsdnVzL2NvbW1vbi5wcm90byI9ChJSZXNvdXJjZUdyb3VwT
  GltaXQSJwoIbm9kZV9udW0YASABKAVCDOI/CRIHbm9kZU51bVIHbm9kZU51bSJSChVSZXNvdXJjZUdyb3VwVHJhbnNmZXISOQoOc
  mVzb3VyY2VfZ3JvdXAYASABKAlCEuI/DxINcmVzb3VyY2VHcm91cFINcmVzb3VyY2VHcm91cCJuChdSZXNvdXJjZUdyb3VwTm9kZ
  UZpbHRlchJTCgtub2RlX2xhYmVscxgBIAMoCzIhLm1pbHZ1cy5wcm90by5jb21tb24uS2V5VmFsdWVQYWlyQg/iPwwSCm5vZGVMY
  WJlbHNSCm5vZGVMYWJlbHMixQMKE1Jlc291cmNlR3JvdXBDb25maWcSTgoIcmVxdWVzdHMYASABKAsyIy5taWx2dXMucHJvdG8uc
  mcuUmVzb3VyY2VHcm91cExpbWl0Qg3iPwoSCHJlcXVlc3RzUghyZXF1ZXN0cxJICgZsaW1pdHMYAiABKAsyIy5taWx2dXMucHJvd
  G8ucmcuUmVzb3VyY2VHcm91cExpbWl0QgviPwgSBmxpbWl0c1IGbGltaXRzEl4KDXRyYW5zZmVyX2Zyb20YAyADKAsyJi5taWx2d
  XMucHJvdG8ucmcuUmVzb3VyY2VHcm91cFRyYW5zZmVyQhHiPw4SDHRyYW5zZmVyRnJvbVIMdHJhbnNmZXJGcm9tElgKC3RyYW5zZ
  mVyX3RvGAQgAygLMiYubWlsdnVzLnByb3RvLnJnLlJlc291cmNlR3JvdXBUcmFuc2ZlckIP4j8MEgp0cmFuc2ZlclRvUgp0cmFuc
  2ZlclRvEloKC25vZGVfZmlsdGVyGAUgASgLMigubWlsdnVzLnByb3RvLnJnLlJlc291cmNlR3JvdXBOb2RlRmlsdGVyQg/iPwwSC
  m5vZGVGaWx0ZXJSCm5vZGVGaWx0ZXJCcAoOaW8ubWlsdnVzLmdycGNCElJlc291cmNlR3JvdXBQcm90b1ABWjBnaXRodWIuY29tL
  21pbHZ1cy1pby9taWx2dXMtcHJvdG8vZ28tYXBpL3YyL3JncGKgAQGqAhJNaWx2dXMuQ2xpZW50LkdycGNiBnByb3RvMw=="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      io.milvus.grpc.common.CommonProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}